### ISSUE TITLE
Utilities Cron Job in FastAPI

### ISSUE THREAD

**Issue by umar-anzar** [Hoopoes/CodersInventory#39]
Add this in Utilities 

```toml
typing-inspect = "^0.9.0"
fastapi-utils = "^0.8.0"
```

```py
from fastapi_utils.tasks import repeat_every
from contextlib import asynccontextmanager

# 1 min
@repeat_every(seconds=60 * 1)
async def cron_job():
    print("CronJob....")

@asynccontextmanager
async def lifespan(app: FastAPI):
    await cron_job()
    yield


app = FastAPI(lifespan=lifespan)
```
